### ISSUE TITLE
No value populated for digitrust id in latest version.

### ISSUE THREAD

**Issue by pm-manasi-moghe** [digi-trust/dt-cdn#65] opened 2019-04-04 09:47 UTC
Hi,

Working with the latest releases, we are not able to get the value of digitrust id set in the cookie "DigiTrust.v1.identity". 
There is no cookie created on the page domain, hence there is no digitrust id available. 
It seems to work on the version 1.5.15. 

Any help regarding this would be appreciated.

Thanks and Regards

**Comment by goosemanjack** [comment] 2019-04-04 16:04
Can you please specify the browser and platform used. Also, if there is a public example of your hosting please include the link.

**Comment by pm-manasi-moghe** [comment] 2019-04-08 07:16
Browser: Chrome
Platform: Ubuntu
Will share a link to a test page shortly.

**Comment by pm-manasi-moghe** [comment] 2019-04-16 07:04
hi @goosemanjack,

Any update on this? Were you able to reproduce the issue with the test pages?

**Comment by pm-shashank-jain** [comment] 2019-06-26 04:46
Hi @goosemanjack ,
Any update on this ?

**Comment by goosemanjack** [comment] 2019-07-08 18:50
I've been unable to reproduce this and your fiddle has a number of issues that error out. I also see that Prebid is included in your sample. You may wish to migrate to the integrated DigiTrust/Prebid system if that is the case.

There are a number of environment and browser-related issues that could surface in this behavior which are unrelated to DigiTrust. Chrome, Safari, and FireFox have all been changing their behaviors for third party cookies. Your test and production environments should also be using SSL (https) for optimal behavior. Based on your description I believe this is tied to behavioral changes at the browser level WRT 3rd party cookie treatment. I will keep an eye out for a solid reproduction outside of our known environmental issues, but am going to close this issue as no-repro.

**Closed by goosemanjack** 2019-07-08 18:50 UTC
